spring.application.name=auth
server.port=5000
jwt.secret=H2qZ7uR6o4m8jPMg8Wkq9aN3Zqv0rBfGJmW6sS7Kc2E=

# Aquí eliges qué entorno encender: "dev", "test-local" o "prod-aws"
spring.profiles.active=prod-aws